### PR TITLE
[BUGFIX] for #144. #145, $extensKeyOrArray

### PR DESCRIPTION
**Pull request by Madii**
Now if $extensKeyOrArray is an array it goes throw it ...sry couldn't wait for a solution so i made it myself ;-)

### CODE REVIEW

**Comment by NamelessCoder** [comment]
This is actually incorrect. There is no need to iterate the `$extensionKeyOrArray` - as the variable says, it literally holds either an extension **key** or the extension description **array**. If it is an array, the values are extension key, label and icon - and those values are extracted using `list()`.

It is possible you are registering your variants incorrectly (e.g. missing an extension key segment in the array location you use). Either way, this PR would break processing of correctly registered variants and must be rejected - sorry!

**Comment by NamelessCoder** [comment]
Actually, it's only half incorrect. It's correct that an extra level of iteration is required - but if done this way it would result in incorrect icon resolving and inappropriate variable names. Fix is coming, thanks for pointing it out!

**Comment by Madii** [comment]
You are not right. As in your description i register a new variant by
`$GLOBALS['TYPO3_CONF_VARS']['FluidTYPO3.FluidcontentCore']['variants']['text'][] = 'extensionkey';` for example.
That results in $extensionkeyOrArray = *array*('extensionkey')
So if it goes threw this 
````php
if (TRUE === is_array($extensionKeyOrArray) && 3 === count($extensionKeyOrArray)) {
					list ($extensionKey, $labelReference, $icon) = $extensionKeyOrArray;
				} elseif (TRUE === is_array($extensionKeyOrArray) && 2 === count($extensionKeyOrArray)) {
					list ($extensionKey, $labelReference) = $extensionKeyOrArray;
				} else {
					$extensionKey = ExtensionNamingUtility::getExtensionKey($extensionKeyOrArray);
					$labelReference = 'fluidcontent_core.variantLabel';
				}
````
it will call `ExtensionNamingUtility::getExtensionKey(array) ` which results in an error because this method needs an string!

**Comment by Madii** [comment]
Hehe :) ...no problem. Your welcome Clause

**Comment by Madii** [comment]
Oh and your right about the icons and inappropriate variable names. My mistake.

**Comment by NamelessCoder** [comment]
Applied in https://github.com/FluidTYPO3/fluidcontent_core/commit/c1b8ef55d1086f8c6d74be3499d1d916e8a57fd3

**Comment by Madii** [comment]
:+1:

**Pull request closed without merging**
