### PR TITLE
Update ConfigurationService.php

### PR DESCRIPTION
**Pull request by rabe69**
$variant is not defined. I think it should be $variants.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Should be `$paths = $this->getViewConfigurationForExtensionName($extensionKey);` - the method expects an extension name and passing `$variants` would give it an array; `$extensionKey` was extracted a few lines above and should be safe to use.

**Comment by cedricziel** [comment]
Hijacked it with you as author to move a little faster.

Thank you for your conribution!

**Comment by rabe69** [comment]
o.k., thanks. Sorry i was quite busy...

**Comment by cedricziel** [comment]
No excuses necessary. We just wanted to short circuit this a bit :)

Thank you for the PR

**Pull request closed without merging**
